StoreApp/StoreApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelLayer.Models;
using ModelLayer.ViewModels;

namespace StoreApp.Controllers
{
    public class CustomerController : Controller
    {
        private BusinessLogicClass _logic;

        public CustomerController(BusinessLogicClass logic)
        {
            _logic = logic;
        }

        // GET: CustomerController
        public ActionResult Index(CustomerInfoViewModel loggedInView)
        {

            if (loggedInView.CustomerFName == null)
            {
                Guid id = new Guid(HttpContext.Session.GetString("customerId"));
                CustomerInfoViewModel customerInfo = _logic.GetCustomerById(id);

                if (customerInfo == null)
                {
                    RedirectToAction("Index", "Home");
                }

                customerInfo.PerferedStore = _logic.GetNewStoreById(customerInfo.StoreId);

                return View(customerInfo);
            }

            loggedInView.PerferedStore = _logic.GetNewStoreById(loggedInView.StoreId);

            return View(loggedInView);
        }

        // GET: CustomerController/Details/5
        [HttpGet]
        public ActionResult Details(Guid id)
        {
            CustomerInfoViewModel customerInfo = _logic.GetCustomerById(id);

            if (customerInfo == null)
            {
                ModelState.AddModelError("Failure", "Customer does not exist");
                return View(customerInfo);
            }

            return View(customerInfo);
        }

        [HttpGet]
        public IActionResult GetAllCustomers()
        {
            CustomerListViewModel customerList = _logic.GetCustomerList();
            return View(customerList);
        }


        // GET: CustomerController/Edit/5
        public ActionResult Edit(Guid id)
        {
            CustomerInfoViewModel customerToEdit = _logic.GetCustomerById(id);

            if (customerToEdit == null)
            {
                ModelState.AddModelError("Failure", "Customer does not exist to edit");
                return View(customerToEdit);
            }

            List<string> storeNames = _logic.GetStoreNames();

            ViewBag.StoreNames = new SelectList(storeNames);

            return View(customerToEdit);
        }

        public ActionResult EditPlayer(CustomerInfoViewModel customerToEdit)
        {
            CustomerInfoViewModel editedCustomer = _logic.EditCustomer(customerToEdit);

            if (editedCustomer == null)
            {
                ModelState.AddModelError("Failure", "Customer does not exist");
                return View("Edit", editedCustomer);
            }

            return View("Details", editedCustomer);
        }

        // POST: CustomerController/Edit/5
        // LOOK INTO THIS???
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        

       
    }
}

StoreApp/StoreApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelLayer.ViewModels;

namespace StoreApp.Controllers
{
    public class LoginController : Controller
    {
        private BusinessLogicClass _logic;

        public object Session { get; private set; }

        public LoginController(BusinessLogicClass logic)
        {
            _logic = logic;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoginCustomer(LoginViewModel loginView)
        {
            CustomerInfoViewModel customerLoggingIn = _logic.LoginUser(loginView);
            if (customerLoggingIn == null)
            {
                ModelState.AddModelError("Failure", "Wrong Username and password combination!");
                return View("Index");
            }

            HttpContext.Session.SetString("customerId", customerLoggingIn.CustomerID.ToString());
            HttpContext.Session.SetString("isAdmin", customerLoggingIn.isAdmin.ToString());

            return RedirectToAction("Index", "Customer", customerLoggingIn);
        }

        [ActionName("NewCustomer")]
        public IActionResult LoginCustomer(CustomerInfoViewModel newUser)
        {
            if (newUser == null)
            {
                ModelState.AddModelError("Failure", "Wrong Username and password combination!");
                return View("Index");
            }

            HttpContext.Session.SetString("customerId", newUser.CustomerID.ToString());
            HttpContext.Session.SetString("isAdmin", newUser.isAdmin.ToString());
            return RedirectToAction("Index", "Customer", newUser);
        }


        public IActionResult CreateCustomer()
        {
            List<string> storeNames = _logic.GetStoreNames();

            ViewBag.StoreNames = new SelectList(storeNames);

            return View();
        }

        public IActionResult CreateNewCustomer(CreateCustomerViewModel signUpView)
        {
            CustomerInfoViewModel customerCreated = _logic.CreateUser(signUpView);

            if (customerCreated == null)
            {
                ModelState.AddModelError("Failure", "Username already exists");
                return View("CreateCustomer");
            }

            return RedirectToAction("NewCustomer", customerCreated);
        }

       public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            return RedirectToAction("Index", "Home");
        }
    }
}

StoreApp/StoreApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Mvc;
using ModelLayer.ViewModels;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
  
        private BusinessLogicClass _logic;

        public ProductController(BusinessLogicClass logic)
        {
            _logic = logic;
        }

        public IActionResult Index()
        {
            ProductListViewModel productList = _logic.GetProductList();
            return View(productList);
        }

        public IActionResult CreateProduct()
        {
            return View();
        }

        public IActionResult CreateNewProduct(ProductInfoViewModel newProduct)
        {

            ProductInfoViewModel productCreated = _logic.CreateProduct(newProduct);

            if (productCreated == null)
            {
                ModelState.AddModelError("Failure", "Product already exists");
                return View("CreateProduct");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid id)
        {
            ProductInfoViewModel productDetails = _logic.GetProductById(id);

            if (productDetails == null)
            {
                ModelState.AddModelError("Failure", "Product does not exist");
                return View(productDetails);
            }

            return View(productDetails);
        }

        public IActionResult Edit(Guid id)
        {
            ProductInfoViewModel productToEdit = _logic.GetProductById(id);
            if (productToEdit == null)
            {
                ModelState.AddModelError("Failure", "Product does not exist");
                return View(productToEdit);
            }

            return View(productToEdit);
        }

        public IActionResult EditProduct(ProductInfoViewModel productToEdit)
        {
            ProductInfoViewModel editedProduct = _logic.EditProduct(productToEdit);

            if (editedProduct == null)
            {
                ModelState.AddModelError("Failure", "Product does not exist");
                return View("Edit", editedProduct);
            }

            return View("Details", editedProduct);
        }



    }
}

StoreApp/StoreApp/Views/Customer/Details.cshtml
@model ModelLayer.ViewModels.CustomerInfoViewModel

@{
    ViewData["Title"] = "Details";
}

@{
    @using Microsoft.AspNetCore.Http;
    @inject IHttpContextAccessor HttpContextAccessor
    var isAdmin = @HttpContextAccessor.HttpContext.Session.GetString("isAdmin");
}

<h1>Details</h1>

<div style="color:red;">@Html.ValidationSummary()</div>
<div class="row">
    <!--Show details are saved successfully message-->
    <div class="col-lg-12">@ViewBag.Message</div>
</div>

<div>
    <h4>CustomerInfoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerUserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerUserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerFName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerFName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerLName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerLName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerAge)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerAge)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerBirthday)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerBirthday)
        </dd>
        @if (isAdmin.ToLower() == "true")
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.isAdmin)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.isAdmin)
            </dd>
        }

    </dl>
</div>


<div>
    @if (Model != null)
    {
        <a asp-controller="Customer" asp-action="Edit" asp-route-id="@Model.CustomerID" method="get">Edit Profile</a>
    }
    @if (isAdmin.ToLower() == "true")
    {
        <span> | </span>
        <a asp-controller="Customer" asp-action="GetAllCustomers" method="get">Back to List</a>
    }

</div>

StoreApp/StoreApp/Views/Customer/Edit.cshtml
@model ModelLayer.ViewModels.CustomerInfoViewModel

@{
    ViewData["Title"] = "Edit";
}

@{
    @using Microsoft.AspNetCore.Http;
    @inject IHttpContextAccessor HttpContextAccessor
    var isAdmin = @HttpContextAccessor.HttpContext.Session.GetString("isAdmin");
}

<h1>Edit</h1>

<div style="color:red;">@Html.ValidationSummary()</div>
<div class="row">
    <!--Show details are saved successfully message-->
    <div class="col-lg-12">@ViewBag.Message</div>
</div>

@if (Model != null)
{
    <h4>CustomerInfoViewModel</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="EditPlayer">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="CustomerID" class="control-label"></label>
                    <input asp-for="CustomerID" class="form-control" />
                    <span asp-validation-for="CustomerID" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerUserName" class="control-label"></label>
                    <input asp-for="CustomerUserName" class="form-control" />
                    <span asp-validation-for="CustomerUserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerFName" class="control-label"></label>
                    <input asp-for="CustomerFName" class="form-control" />
                    <span asp-validation-for="CustomerFName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerLName" class="control-label"></label>
                    <input asp-for="CustomerLName" class="form-control" />
                    <span asp-validation-for="CustomerLName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerAge" class="control-label"></label>
                    <input asp-for="CustomerAge" class="form-control" />
                    <span asp-validation-for="CustomerAge" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerBirthday" class="control-label"></label>
                    <input asp-for="CustomerBirthday" class="form-control" />
                    <span asp-validation-for="CustomerBirthday" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="StoreNameChosen" class="control-label"></label>
                    <select asp-for="StoreNameChosen" asp-items="@ViewBag.StoreNames"></select>
                    <span asp-validation-for="StoreNameChosen" class="text-danger"></span>
                </div>
                @if (isAdmin.ToLower() == "true")
                {
            <div class="form-group">
                <label asp-for="isAdmin" class="control-label"></label>
                <input asp-for="isAdmin" class="form-control" />
                <span asp-validation-for="isAdmin" class="text-danger"></span>
            </div>
                }
                    
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

StoreApp/StoreApp/Views/Customer/GetAllCustomers.cshtml
@model ModelLayer.ViewModels.CustomerListViewModel

@{
    ViewData["Title"] = "GetAllCustomers";
}

<h1>All Customers</h1>


<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var customer in Model.Customers) {
        <tr>
            <td>
                @customer.CustomerFName @customer.CustomerLName
                <a asp-controller="Customer" asp-action="Details" asp-route-id="@customer.CustomerID" method="get">Details</a> |
                <a asp-controller="Customer" asp-action="Edit" asp-route-id="@customer.CustomerID" method="get">Edit Profile</a>

            </td>
        </tr>
}
    </tbody>
</table>

<a asp-controller="Customer" asp-action="Index">Back To Dashboard</a>

StoreApp/StoreApp/Views/Customer/Index.cshtml
@model ModelLayer.ViewModels.CustomerInfoViewModel
@{
    ViewData["Title"] = "Dashboard";
}

@{
    @using Microsoft.AspNetCore.Http;
    @inject IHttpContextAccessor HttpContextAccessor
    var isAdmin = @HttpContextAccessor.HttpContext.Session.GetString("isAdmin");
}

    <h1>Welcome @Model.CustomerFName!</h1>

<a asp-controller="Shop" asp-action="Store" asp-route-id=" @Model.PerferedStore.StoreLocationId">Quick Shop!</a>
<br />
<a asp-controller="Shop" asp-action="Index">Shop!</a>
<br />
<a asp-controller="Customer" asp-action="Details" asp-route-id="@Model.CustomerID" method="get">Details</a>
<br />
<a asp-controller="Login" asp-action="Logout">Log Out</a>
@if (isAdmin.ToLower() == "true")
{
    <br />
    <a asp-controller="Shop" asp-action="CreateStore">Create Store Location</a>
    <br />
    <a asp-controller="Product" asp-action="Index" method="get">Manage Products</a>
    <br />
    <a asp-controller="Customer" asp-action="GetAllCustomers" method="get">Manage Customers</a>
}