StoreApp/StoreApp/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ModelLayer.Models;
using ModelLayer.ViewModels;

namespace StoreApp.Controllers
{
    public class CustomerController : Controller
    {
        private BusinessLogicClass _logic;

        public CustomerController(BusinessLogicClass logic)
        {
            _logic = logic;
        }

        // GET: CustomerController
        public ActionResult Index(CustomerInfoViewModel loggedInView)
        {

            if (loggedInView.CustomerFName == null)
            {
                Guid id = new Guid(HttpContext.Session.GetString("customerId"));
                CustomerInfoViewModel customerInfo = _logic.GetCustomerById(id);

                if (customerInfo == null)
                {
                    RedirectToAction("Index", "Home");
                }

                customerInfo.PerferedStore = _logic.GetNewStoreById(customerInfo.StoreId);

                return View(customerInfo);
            }

            loggedInView.PerferedStore = _logic.GetNewStoreById(loggedInView.StoreId);

            return View(loggedInView);
        }

        // GET: CustomerController/Details/5
        [HttpGet]
        public ActionResult Details(Guid id)
        {
            CustomerInfoViewModel customerInfo = _logic.GetCustomerById(id);

            if (customerInfo == null)
            {
                ModelState.AddModelError("Failure", "Customer does not exist");
                return View(customerInfo);
            }

            return View(customerInfo);
        }

        [HttpGet]
        public IActionResult GetAllCustomers()
        {
            CustomerListViewModel customerList = _logic.GetCustomerList();
            return View(customerList);
        }


        // GET: CustomerController/Edit/5
        public ActionResult Edit(Guid id)
        {
            CustomerInfoViewModel customerToEdit = _logic.GetCustomerById(id);

            if (customerToEdit == null)
            {
                ModelState.AddModelError("Failure", "Customer does not exist to edit");
                return View(customerToEdit);
            }

            List<string> storeNames = _logic.GetStoreNames();

            ViewBag.StoreNames = new SelectList(storeNames);

            return View(customerToEdit);
        }

        public ActionResult EditPlayer(CustomerInfoViewModel customerToEdit)
        {
            CustomerInfoViewModel editedCustomer = _logic.EditCustomer(customerToEdit);

            if (editedCustomer == null)
            {
                ModelState.AddModelError("Failure", "Customer does not exist");
                return View("Edit", editedCustomer);
            }

            return View("Details", editedCustomer);
        }

        // POST: CustomerController/Edit/5
        // LOOK INTO THIS???
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        

       
    }
}

StoreApp/StoreApp/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLogicLayer;
using Microsoft.AspNetCore.Mvc;
using ModelLayer.ViewModels;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
  
        private BusinessLogicClass _logic;

        public ProductController(BusinessLogicClass logic)
        {
            _logic = logic;
        }

        public IActionResult Index()
        {
            ProductListViewModel productList = _logic.GetProductList();
            return View(productList);
        }

        public IActionResult CreateProduct()
        {
            return View();
        }

        public IActionResult CreateNewProduct(ProductInfoViewModel newProduct)
        {

            ProductInfoViewModel productCreated = _logic.CreateProduct(newProduct);

            if (productCreated == null)
            {
                ModelState.AddModelError("Failure", "Product already exists");
                return View("CreateProduct");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Details(Guid id)
        {
            ProductInfoViewModel productDetails = _logic.GetProductById(id);

            if (productDetails == null)
            {
                ModelState.AddModelError("Failure", "Product does not exist");
                return View(productDetails);
            }

            return View(productDetails);
        }

        public IActionResult Edit(Guid id)
        {
            ProductInfoViewModel productToEdit = _logic.GetProductById(id);
            if (productToEdit == null)
            {
                ModelState.AddModelError("Failure", "Product does not exist");
                return View(productToEdit);
            }

            return View(productToEdit);
        }

        public IActionResult EditProduct(ProductInfoViewModel productToEdit)
        {
            ProductInfoViewModel editedProduct = _logic.EditProduct(productToEdit);

            if (editedProduct == null)
            {
                ModelState.AddModelError("Failure", "Product does not exist");
                return View("Edit", editedProduct);
            }

            return View("Details", editedProduct);
        }



    }
}

StoreApp/StoreApp/Views/Product/CreateProduct.cshtml
@model ModelLayer.ViewModels.ProductInfoViewModel

@{
    ViewData["Title"] = "CreateProduct";
}

<h1>CreateProduct</h1>

<div style="color:red;">@Html.ValidationSummary()</div>
<div class="row">
    <!--Show details are saved successfully message-->
    <div class="col-lg-12">@ViewBag.Message</div>
</div>

<h4>ProductInfoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewProduct">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDesc" class="control-label"></label>
                <input asp-for="ProductDesc" class="form-control" />
                <span asp-validation-for="ProductDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAgeRestricted" /> @Html.DisplayNameFor(model => model.IsAgeRestricted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StoreApp/StoreApp/Views/Product/Details.cshtml
@model ModelLayer.ViewModels.ProductInfoViewModel

@{
    ViewData["Title"] = "Details";
}

<div style="color:red;">@Html.ValidationSummary()</div>
<div class="row">
    <!--Show details are saved successfully message-->
    <div class="col-lg-12">@ViewBag.Message</div>
</div>

<h1>Details</h1>

<div>
    <h4>ProductInfoViewModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductDesc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductDesc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsAgeRestricted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsAgeRestricted)
        </dd>
    </dl>
</div>
<div>
    @if (true)
    {
        <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.ProductID">Edit</a>
    }
    | <a asp-action="Index">Back to List</a>
</div>

StoreApp/StoreApp/Views/Product/Edit.cshtml
@model ModelLayer.ViewModels.ProductInfoViewModel

@{
    ViewData["Title"] = "Edit";
}

<div style="color:red;">@Html.ValidationSummary()</div>
<div class="row">
    <!--Show details are saved successfully message-->
    <div class="col-lg-12">@ViewBag.Message</div>
</div>

<h1>Edit</h1>

<h4>ProductInfoViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditProduct">
            <div class="form-group">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <label asp-for="ProductID" class="control-label"></label>
                <input asp-for="ProductID" class="form-control" />
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductDesc" class="control-label"></label>
                <input asp-for="ProductDesc" class="form-control" />
                <span asp-validation-for="ProductDesc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductPrice" class="control-label"></label>
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsAgeRestricted" /> @Html.DisplayNameFor(model => model.IsAgeRestricted)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

StoreApp/StoreApp/Views/Product/Index.cshtml
@model ModelLayer.ViewModels.ProductListViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="CreateProduct">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var product in Model.Products) {
        <tr>
            <td>
                @product.ProductName |
                @product.ProductDesc |
                @product.ProductPrice |
                @product.IsAgeRestricted |
                @product.ProductID

                <a asp-controller="Product" asp-action="Details" asp-route-id="@product.ProductID">Product details</a> |
                <a asp-controller="Product" asp-action="Edit" asp-route-id="@product.ProductID">Edit Product</a>
            </td>
        </tr>
}
    </tbody>
</table>

<a asp-controller="Customer" asp-action="Index">Back to dashboard</a>